### ISSUE TITLE
Unable to install cytoflow

### ISSUE THREAD

**Issue by luisawachtendonk** [cytoflow/cytoflow#360]
Hey there, I was impressed by your work and would love to use cytoflow. However, I was sadly unable to install it. The conda environment on the master seems to be broken, and I was also unable to install from an older branch. Sadly, I cannot install from Anaconda due to licensing reasons. Would you consider a release on conda-forge?

### PLATFORM (Mac, PC, Linux, other):
PC

### OPERATING SYSTEM (eg OSX 10.7, Windows 8.1):
Windows 10

### SEVERITY (Critical? Major? Minor? Enhancement?):
Critical

### DESCRIPTION:
  - What were you trying to do?
   Trying to install cytoflow according to the "HOWTO: Install Cytoflow Modules" guide on the readthedocs page. Tried both "Installing from the command line" and "To hack on the code".

  - What happened?
  It did not work

**Comment by benweinberg89** [comment]
@luisawachtendonk did you get the same logical issue that I got in #359 ?

I'm a little confused by your issues with licensing. If your institution has over 200 people, then you can't use packages in the "default" channel for free, but I think you may be able to use cytoflow as its from its own "cytoflow" channel rather than default? The latest version of cytoflow on conda seems to be 1.2 and was uploaded 3 years ago, it should be functional. Make sure you are using python 3.8 for that version.

I made a fork a couple months ago and I believe I was successful with running that using the "hack the code" instructions. I made one commit to it, but perhaps roll back to one commit before that.

Also, try to be a bit more descriptive in your issue. What specifically didn't work?

**Comment by michaelosthege** [comment]
I'm a colleague of @luisawachtendonk, so I can reproduce some of the installation issues.

I think our IT department started blocking the `default` Anaconda channel as a precaution, resulting in errors such as `CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://repo.anaconda.com/pkgs/main/linux-64/repodata.json>`.

Changing `defaults`→`conda-forge` in the `environment.yml` was not enough, because the exact combination of pinned packages is not available on the forge.

However, I got it working by unpinning the conflicting packages one by one while checking with `mamba env create -f environment.yml --dry-run`.

I ended up with this `environment.yml` 👇

```yaml
name: cytoflow
channels:
 - conda-forge
 
dependencies:
    - python=3.11.11
    - numpy==1.26.4
    - pandas==2.2.3
    - matplotlib  #==3.9.2
    - bottleneck==1.4.2
    - numexpr==2.10.1
    - scipy==1.14.1
    - scikit-learn==1.5.2
    - seaborn==0.13.2
    - statsmodels==0.14.4
    - natsort==7.1.1
    - numba==0.60.0

    - traits  #==6.2.0
    - conda-forge::traitsui==8.0.0
    - conda-forge::pyface==8.0.0
    - conda-forge::envisage==7.0.3
    - nbformat==5.10.4
    - python-dateutil  #==2.9.0post0
    - importlib_resources==6.4.0

    - qt==5.15.*
    - pyqt==5.15.*
    - pyqtwebengine=5.15.*

    - cytoflow::camel==0.1.2
    - yapf  #==0.40.2
    
    - ipympl
    - notebook
    
    - nomkl # [not win]
```

The environment creation suceeded and with `python -c "import cytoflow"` I now run into #359 too.
